FROM node:slim

WORKDIR /express-docker

COPY ./package.json .
RUN npm install

COPY . .

RUN ["mv", "docker.env", ".env"]
RUN ["echo", "STEAMKEY=${STEAMKEY:=XXXX-XXXX-XXXX-XXXX}", ">>", ".env"]

CMD [ "node", "--env-file=.env", "index.js" ]

EXPOSE 3000